### ISSUE TITLE
Clicking image space leads to error

### ISSUE THREAD

**Issue by chrismattmann** [ContinuumIO/memex-explorer#276]
After a crawl is done (I had to stop it manually and restart the app), I can browse to a project and see the image space (after calling get images). After doing so, i clicked the image space and got this:

```
AttributeError
AttributeError: 'NoneType' object has no attribute 'images'

Traceback (most recent call last)
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/root/anaconda/envs/memex-explorer/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/memex-explorer/app/views.py", line 562, in image_table
images = image_space.images.all()
AttributeError: 'NoneType' object has no attribute 'images'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by brittainhard** [comment]
This is connected to #275 . This error is happening because the crawl did not finish it's around, and therefore did not register an image space.
